Урок 3
Матрицы и матричные операции. Часть 1

1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .

Для произведения матриц, необходимо,чтобы количество столбцов одной матрицы равнялось количеству строк другой матрицы.
Произведение матриц определено в случае "в" и "г". 

в) Размерность матрицы С = АВ будет 8 * 8, размерность матрицы D = ВА будет 3*3

г) Размерность полученных матриц будет 4*4 

2. Найти сумму и произведение матриц.

In [6]:
import numpy as np

In [16]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Матрица A:\n{A}')
print(f'Матрица B:\n{B}')

Матрица A:
[[ 1 -2]
 [ 3  0]]
Матрица B:
[[ 4 -1]
 [ 0  5]]


In [11]:
print(f'Матрица С = A + B\n{A + B}')

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]


In [12]:
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица AB
[[  4 -11]
 [ 12  -3]]


In [13]:
print(f'Матрица BA\n{B.dot(A)}')


Матрица BA
[[ 1 -8]
 [15  0]]


3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию  3A−2B+4C  для матриц  A=(137−6) ,  B=(025−1) ,  C=(21−41).

4. Дана матрица  A=⎛⎝⎜4521−23⎞⎠⎟ . Вычислить  AAT  и  ATA .

In [15]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]


In [17]:
A_trans = A.T
A_trans

array([[ 1,  3],
       [-2,  0]])

In [18]:
AAT = np.dot(A, A_trans)
AAT

array([[5, 3],
       [3, 9]])

In [19]:
ATA = np.dot(A_trans, A)
ATA

array([[10, -2],
       [-2,  4]])

Матрицы и матричные операции. Часть 2

Практическое задание

1. Вычислить определитель:

a)

∣∣∣sinxcosx−cosxsinx∣∣∣; 

б)

∣∣∣∣400250319∣∣∣∣; 

в)

∣∣∣∣147258369∣∣∣∣.

In [20]:
import scipy.linalg

In [23]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


In [24]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


2. Определитель матрицы  A  равен  4 . Найти:

а)  det(A2) ;

б)  det(AT) ;

в)  det(2A) .

det(A**2) = 16

det(AT) = det(A) = 4

det(2A) = 8

3. Доказать, что матрица

⎛⎝⎜−24−37−147−3613⎞⎠⎟ 

вырожденная.

Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю.Вычислим определитель.

In [26]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


4. Найти ранг матрицы:

а)  ⎛⎝⎜112213314⎞⎠⎟; 

б)  ⎛⎝⎜⎜⎜0002000322451236⎞⎠⎟⎟⎟.

In [27]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


In [28]:
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
